name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Release? yes/no'
        default: 'no'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        timeout-minutes: 10
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: build
    if: github.event.inputs.release == 'yes'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        run: |
          ./gradlew release \
              -Prelease.customUsername=${{ github.actor }} \
              -Prelease.customPassword=${{ github.token }}
          ./gradlew publishPlugins -Pgradle.publish.key=${{ vars.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
